### PR TITLE
Better Module Setup

### PR DESCRIPTION
**Pull request by ChrisMBarr**
This allows for a better module setup in the generated files. now it generates two modules so that a consuming application can decide which one to use.  I have used this same setup on my [`OpenLyrics-Parser`](https://github.com/FiniteLooper/OpenLyrics-parser) and [`SongShowPlus-parser`](https://github.com/FiniteLooper/SongShowPlus-parser) projects and it works great.

Files are also re-organized a bit.  Now the main entry point is `index.ts/js` and everything is exported from there. The index file is very simple now, it just exports a single function and the TS interfaces.  All TS interfaces now exist in their own file `parser.models.ts`

All code related to the parser is now in a `parser.ts` file, and it no longer consists of `static` members only.

Splitting the parser up this way allows for a future update where a `SongProBuilder` could be added to create files based on data passed into it.

No functionality with the parser was actually changed.  The only thing that is different to a consumer is the usage.

**Before**
```js
const { SongPro } = require('songpro');
let song = SongPro.parse(contents);
```

**Now**
```js
const { SongProParser } = require('songpro');
let song = SongProParser(contents);
```

### CODE REVIEW

**Comment by spilth** [comment]
My main hesitation here is that I've been trying to keep the various library APIs in sync,  so if we change the JavaScript API then we should change all of them. But also maybe we don't?

I personally don't have any issue with the parser being a static method - it's not a long lived object and doesn't need any of it's own state.

I might need to mull this over for a bit.

Additionally, for changes like this in the future I think we should create an Issue first so we can discuss things before putting a bunch of work into something. For one thing it changes the API and isn't backwards compatible (users need to change their code), so we should probably bump the major version number. But I could also argue that a) we don't really have many users yet and b) we're still in a sub-1.0 release. 🤷🏻 

I appreciate your work and your enthusiasm but I'd like to balance that with consistency across the different libraries and discussion so the format has a unified front.

**Comment by ChrisMBarr** [comment]
You raise a good point.  The API change was probably a bad idea on my part, sorry about that. On some lesser-used things I work on making a change like that is no big deal.

I can easily go back in and make a change so the code is still structured the same as it is now, but the API is identical to how it we before.  Would that work?  Basically it would just change how it is consumed in the `index.ts` file.

My only reason for moving off the all-static class was due to the ESLint rule [`no-extraneous-class`](https://typescript-eslint.io/rules/no-extraneous-class/) which flagged this.  We can certainly turn this rule off and go back to using static classes as namespaces though, there's nothing "wrong" about that IMO.

**Comment by ChrisMBarr** [comment]
Ok, just pushed a change that will keep the API exactly the same as before. This is how it should have been from the start. Apologies.

I've tested this as working the same in my LyricConverter project.  No API changes, all tests pass there and within this project.

**Comment by spilth** [comment]
No worries - I'm just glad we can have a discussion about it and come to an agreement.

I also think it's good to break up different concerns into different Issues/PRs, that way it's easier to rollback an individual thing by reverting the commit and not undoing a bunch of other things. It also helps keep discussion focused on a single topic.

For example, the spelling configuration, editorconfig and prettier config could be their own Issues/PRs separate of the module changes. I won't reject them this time but something to keep in mind for the future. Also, I'm totally guilty of combining to many things into PRs all the time - it's easier to get away with and not check yourself on personal projects!

**Comment by ChrisMBarr** [comment]
Yep, you make good points.  If you'd like I can close this PR and separate those out into separate PR's.  Doing that might clean up the commit history as well since this one now has some "undo" commits in it.  I am totally able to do that today if you'd like.

However these changes get put in this library, it now has the ability to more easily add features. The only thing I'd imagine it would need would be the ability to create/build SongPro files based on some kind of input.  That can be added just by adding new files that don't modify anything that has to do with the parser.  When that time comes around I will most certainly open up a discussion since we'd want to be sure the API to do that is done in a way that makes sense.

**Comment by spilth** [comment]
It's up to you if you want to break those out as separate PRs. I'm fine to include them this time.

**Comment by spilth** [comment]
Also, FWIW, @Dahie has worked on a version of the Ruby Gem that can read ChordPro files and makes a SongPro object (which could potentially then output a SongPro text file). 

That might be worth starting a discussion about, especially since I'd like to make it easy to import ChordPro files and convert them to SongPro files.

**Review by spilth — APPROVED** [review]

**Comment by ChrisMBarr** [comment]
I'm currently working on [a ProPresenter parser/builder](https://github.com/FiniteLooper/ProPresenter-Parser). Once I get that all working I'll see about focusing on the SongPro builder and start a discussion

**Pull request merged**
